"""
Conceptual Model Writer

Writes `conceptual_model.json`, `conceptual_model.md` and
`conceptual_model.html` from the validated Pydantic model.

The HTML report (see `html_renderer.py`) is the presentation artifact - a
self-contained page with a hand-rendered SVG diagram. The Markdown is kept
alongside it because Mermaid renders natively in GitHub, GitLab and VS Code,
where an HTML file cannot be previewed.

Markdown, Mermaid and HTML are all generated deterministically in code.
The AI is never asked for any of them. Two reasons:

- The AI's job is business judgment, not formatting. Asking it to produce
  Markdown spends tokens on layout and makes the output non-reproducible.
- A diagram derived from the parsed model cannot disagree with the model.
  A diagram the AI writes separately can, and would be believed.

Rendering is a pure function of the model, so the same model always produces
byte-identical output and the artifact can be diffed across runs.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path

from migration.conceptual.html_renderer import render_conceptual_html
from migration.conceptual.models import ConceptualModel, ConceptualModelPackage
from migration.relationship.models import Cardinality

logger = logging.getLogger(__name__)

# Mermaid erDiagram cardinality notation, read left-to-right as
# "<left entity> <symbol> <right entity>".
_MERMAID_CARDINALITY: dict[Cardinality, str] = {
    Cardinality.ONE_TO_ONE: "||--||",
    Cardinality.ONE_TO_MANY: "||--o{",
    Cardinality.MANY_TO_ONE: "}o--||",
    Cardinality.MANY_TO_MANY: "}o--o{",
    Cardinality.UNKNOWN: "||--||",
}


class ConceptualModelWriter:
    """Serializes and renders the conceptual model."""

    def write(
        self, package: ConceptualModelPackage, run_directory: Path
    ) -> tuple[Path, Path, Path]:
        """Write all three artifacts. Returns (json, markdown, html)."""
        return (
            self.write_json(package, run_directory),
            self.write_markdown(package, run_directory),
            self.write_html(package, run_directory),
        )

    def write_json(self, package: ConceptualModelPackage, run_directory: Path) -> Path:
        output_file = run_directory / "conceptual_model.json"
        with open(output_file, "w", encoding="utf-8") as fp:
            json.dump(package.model_dump(mode="json"), fp, indent=4, default=str)
        return output_file

    def write_markdown(self, package: ConceptualModelPackage, run_directory: Path) -> Path:
        output_file = run_directory / "conceptual_model.md"
        with open(output_file, "w", encoding="utf-8") as fp:
            fp.write(self.render_markdown(package))
        return output_file

    def write_html(self, package: ConceptualModelPackage, run_directory: Path) -> Path:
        """Write the self-contained HTML report.

        Rendering lives in `html_renderer.py` so the presentation layer can
        be reused by future reports without touching this writer.
        """
        output_file = run_directory / "conceptual_model.html"
        with open(output_file, "w", encoding="utf-8") as fp:
            fp.write(render_conceptual_html(package))
        return output_file

    # -- Rendering (pure) --------------------------------------------------

    def render_markdown(self, package: ConceptualModelPackage) -> str:
        model = package.conceptual_model
        lines: list[str] = []

        lines += ["# Executive Summary", "", model.summary, ""]
        lines += self._provenance(package)
        lines += self._business_overview(model)
        lines += self._domains(model)
        lines += self._entities(model)
        lines += self._entity_relationships(model)
        lines += self._mermaid(model)
        lines += self._list_section("Business Rules", model.business_rules)
        lines += self._list_section("Assumptions", model.assumptions)
        lines += self._list_section("Recommendations", model.recommendations)

        return "\n".join(lines).rstrip() + "\n"

    # -- Sections ----------------------------------------------------------

    @staticmethod
    def _provenance(package: ConceptualModelPackage) -> list[str]:
        """State plainly that this artifact is AI-generated.

        The other three artifacts are deterministic and can be trusted as
        fact. This one is an interpretation, and a reader who cannot tell
        the difference will over-trust it."""
        model_name = package.generated_by or "an AI model"
        return [
            "> This conceptual model was generated by "
            f"**{model_name}** from the deterministic metadata, profile and "
            "relationship artifacts. It is an interpretation of the business the "
            "database appears to support, and should be reviewed by someone who "
            "knows that business. The Assumptions section lists where "
            "interpretation happened.",
            "",
        ]

    @staticmethod
    def _business_overview(model: ConceptualModel) -> list[str]:
        domain_count = len(model.domains)
        entity_count = len(model.entities)
        relationship_count = sum(len(e.relationships) for e in model.entities)

        lines = ["# Business Overview", ""]
        lines += [
            f"- **Database:** {model.database_name}",
            f"- **Business domains:** {domain_count}",
            f"- **Business entities:** {entity_count}",
            f"- **Entity relationships:** {relationship_count}",
            f"- **Business rules identified:** {len(model.business_rules)}",
            "",
        ]
        return lines

    @staticmethod
    def _domains(model: ConceptualModel) -> list[str]:
        lines = ["# Business Domains", ""]
        if not model.domains:
            return lines + ["_No domains were identified._", ""]

        for domain in model.domains:
            lines += [f"## {domain.name}", "", domain.description, ""]
            if domain.entities:
                lines.append(f"**Entities:** {', '.join(domain.entities)}")
                lines.append("")
        return lines

    @staticmethod
    def _entities(model: ConceptualModel) -> list[str]:
        lines = ["# Business Entities", ""]
        for entity in model.entities:
            lines += [f"## {entity.name}", "", entity.description, ""]

            if entity.business_key:
                lines.append(f"**Business key:** {', '.join(entity.business_key)}")
                lines.append("")
            if entity.attributes:
                lines.append("**Attributes**")
                lines.append("")
                lines += [f"- {attribute}" for attribute in entity.attributes]
                lines.append("")
            if entity.source_tables:
                lines.append(f"**Derived from:** `{'`, `'.join(entity.source_tables)}`")
                lines.append("")
        return lines

    @staticmethod
    def _entity_relationships(model: ConceptualModel) -> list[str]:
        lines = ["# Entity Relationships", ""]

        rows = []
        for entity in model.entities:
            for relationship in entity.relationships:
                participation = "optional" if relationship.is_optional else "mandatory"
                rows.append(
                    f"| {entity.name} | {relationship.verb_phrase} | "
                    f"{relationship.related_entity} | "
                    f"{relationship.cardinality.value.replace('_', '-').lower()} | "
                    f"{participation} |"
                )

        if not rows:
            return lines + ["_No relationships were identified._", ""]

        lines += [
            "| Entity | Relationship | Related Entity | Cardinality | Participation |",
            "|---|---|---|---|---|",
        ]
        lines += rows
        lines.append("")
        return lines

    def _mermaid(self, model: ConceptualModel) -> list[str]:
        """Generate the diagram from the parsed model.

        Two rules that are easy to get wrong:

        - The declared direction is preserved. The verb phrase was written
          for `entity -> related_entity`, so reordering the pair to sort it
          alphabetically would leave the label reading backwards
          ('City is located in Customer').
        - Reciprocal pairs are collapsed. If both Customer->Order and
          Order->Customer are declared they are one edge; emitting both
          would double every line in the diagram.

        Determinism comes from sorting the rendered edge strings, not from
        reordering the entities within an edge.
        """
        lines = ["# Mermaid Diagram", "", "```mermaid", "erDiagram"]

        emitted_pairs: set[frozenset[str]] = set()
        connected: set[str] = set()
        edges: list[str] = []

        for entity in model.entities:
            for relationship in entity.relationships:
                pair = frozenset({entity.name, relationship.related_entity})
                if pair in emitted_pairs:
                    continue
                emitted_pairs.add(pair)

                connected.add(entity.name)
                connected.add(relationship.related_entity)

                symbol = _MERMAID_CARDINALITY.get(relationship.cardinality, "||--||")
                edges.append(
                    f"    {self._mermaid_name(entity.name)} {symbol} "
                    f"{self._mermaid_name(relationship.related_entity)} : "
                    f"{self._mermaid_label(relationship.verb_phrase)}"
                )

        lines += sorted(edges)

        # An entity with no relationships takes part in no edge and would
        # otherwise disappear from the diagram entirely. Declare it so the
        # diagram shows every entity the model defines.
        isolated = [entity.name for entity in model.entities if entity.name not in connected]
        lines += [f"    {self._mermaid_name(name)} {{ }}" for name in sorted(isolated)]

        lines += ["```", ""]
        return lines

    @staticmethod
    def _mermaid_name(name: str) -> str:
        """Mermaid entity identifiers cannot contain spaces or punctuation."""
        cleaned = re.sub(r"[^A-Za-z0-9_]+", "_", name).strip("_").upper()
        return cleaned or "UNNAMED"

    @staticmethod
    def _mermaid_label(phrase: str) -> str:
        """Labels are quoted, so embedded quotes must go."""
        cleaned = re.sub(r'["\n\r]+', " ", phrase or "relates to").strip()
        return f'"{cleaned or "relates to"}"'

    @staticmethod
    def _list_section(title: str, items: list[str]) -> list[str]:
        lines = [f"# {title}", ""]
        if not items:
            return lines + ["_None identified._", ""]
        lines += [f"{index}. {item}" for index, item in enumerate(items, start=1)]
        lines.append("")
        return lines
